### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Halama** [keboola/elastic-writer#1]
- Writer by měl umět posílat SAPI tabulky do indexů. Vyexportované CSV zkonvertuje do JSON a posle do ES.
- Pro load dat bude používat [Bulk load](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)
- Indexy s mapováním musí existovat (nebo v případě default nastavení ES ho to automaticky založí při zápisu, tohle chování by ale mělo být spíš vypnuté). **Nebo by měla být definice mapování součástí konfigurace?**
- Autentizaci zatím řešit nebudeme v první verzi, použije se zatím whitelisting naší IP
- Budeme podporovat verzi Elasticu 1.3 a vyšší (od téhle je podpora na dockeruhubu https://hub.docker.com/_/elasticsearch/ a to se bude hodit pro vývoj)
- Pro vývoj se použije docker-composer který lokálně nahodí požadované verze ES pro TDD, pro inspiraci  https://github.com/keboola/db-writer nebo https://github.com/keboola/php-db-import

Nástřel konfigurace, inspirovaný https://github.com/keboola/db-writer
Konfigurace je rozdělená na dvě části:
- `elastic` - nastavení připojení
  - `host` - host elastic serveru
  - `port` - port elasticu
  - `bulkSize`  - velikost dávky pro bulk load, default bude 10.000
  - `tables` - tabulky které se z KBC budou exportovat, pro každou tabulku:
- `tableId` - id tabulky v SAPI
- `index` - jméno cílového indexu v ES
- `type` - jméno cílového typu v ES
- `id` - jméno primárního klíče - ten bude sloužit jako id dokumentu v ES pro zaindexování
- `export` - příznak jestli se má tabulka exportovat při spuštění konfigurace.

``` json
{
        "elastic": {
            "host": "my.hostname.com",
            "port": 9200,
            "bulkSize": 10000
        },
        "tables": [
            {
                "tableId": "in.c-main.products",
                "index": "production",
                "type": "products",
                "id": "id",
                "export": true
            }
        ]
}
```

Původní writer 
https://bitbucket.org/keboola/elasticsearch-writer-bundle

**Comment by ErikZigo** [comment]
Hotovo, tak to zaviram
