### ISSUE TITLE
Very slow performance

### ISSUE THREAD

**Issue by padak** [keboola/elastic-writer#11]
I realise that elastic writer has very bad performance. From ~64kB/s to ~128kB/s (https://keboola.slack.com/archives/elasticsearch/p1468047356000002). It would be great to investigate why its so slow. Details are in Slack.
Thanks,
Peter

**Comment by ErikZigo** [comment]
Tohle zaviram, podle diskuze to bylo malou pridelenou pameti a swapovanim. Zvetseni pameti komponente zabralo.
https://keboola.slack.com/archives/C03PTR79K/p1468062187000022
