### ISSUE TITLE
Stack trace v KBC eventech

### ISSUE THREAD

**Issue by padak** [keboola/elastic-writer#27]
Do eventů začal Elastic Writer sypat low-level errory.

![image](https://user-images.githubusercontent.com/1427901/49463631-3604c600-f7f9-11e8-9ea3-c9c89127f6bb.png)

(https://connection.eu-central-1.keboola.com/admin/projects/395/jobs/16688946?q=)

**Comment by ErikZigo** [comment]
Upravil jsem logovani tak, aby se app chyby spravne sypaly do critical kanalu. Uz by to do event nic takovyho sypat nemelo.
