### ISSUE TITLE
application error should be user error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/elastic-writer#5]
Tohle by měl bejt user error?

https://papertrailapp.com/groups/23635/events?q=d461325e27dc463fc8d2744c7abcba71

```
{
    "output": "Table out.c-reports.views6 - export start\nTable out.c-reports.views6 export failed. Missing csv file\n",
    "errorOutput": "Table out.c-reports.views6 export failed. Missing csv file\n"
}
```

**Comment by ErikZigo** [comment]
@ondrejhlavacek: Svym zpusobem mozna jo. Ale v tomhle pripade ta komponenta nedostala CSV od docker bundlu.
Jak je to mozny? To by melo failnout uz v tom docker bundlu ne?

**Comment by ErikZigo** [comment]
Projistotu ale proverim, jak se ten ex chova, kdyz do input muppingu da out tabulku.

**Comment by ondrejhlavacek** [comment]
@ErikZigo mám v mailu nějaký odpovědi, ale tady nic nevidím... chtěl jsem najít tu konfiguraci, co jim failovala, ale už je smazaná :-( přijde mi divný, že by to mělo failovat v docker-bundlu (ale ne nemožný), ale potřeboval bych vidět ten config. koukám, že to někde testuješ, můžu s tím nějak pomoct?

**Comment by ErikZigo** [comment]
Fixed in (0.2.1) 3ef77d3e067254a723baf3d52de7503ff4c64df4
